server:
  port: 8088

spring:
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/user-center?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver

# 需要指定对应的模板
fast:
  template: fast-boot

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: net.maku.generator.entity
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true